version: '3.7'

services:
  consul:
    image: consul:1.3.0
    container_name: consul
    environment:
      - SERVICE_8500_IGNORE=true
    ports:
      - "8500:8500"
    logging:
      driver: "none"

  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "consul://consul:8500"

  app:
    image: acim/go-reflex
    container_name: app
    depends_on:
      - consul
    volumes:
      - ./:/app